### PR TITLE
Update sdl2 to 0.32.2

### PR DESCRIPTION
**Pull request by kolen**
I couldn't built `sdl2`'s dependency `rustc-serialize` on my machine, it fails with following error

```
error[E0642]: patterns aren't allowed in methods without bodies
   --> /Users/kolen/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.19/src/serialize.rs:147:45
    |
147 |                                             &f_name: &str,
    |                                             ^^^^^^^
...
error: aborting due to previous error

For more information about this error, try `rustc --explain E0642`.
error: Could not compile `rustc-serialize`.
```

So I updated `sdl2` to latest version.

It had [breaking changes, especially after 0.30](https://github.com/Rust-SDL2/rust-sdl2/blob/master/changelog.md#v030), when `Renderer` was split into `Canvas` and `TextureCreator`. Also, now `Texture` has lifetime parameter, but [it's not possible to store both `TextureCreator` and `Texture`s into the same struct, because they're self-referencing](https://github.com/Rust-SDL2/rust-sdl2/issues/788). Because of this, sdl2 now has `unsafe_textures` feature, which is, AFAIK, similar to behavior before 0.30, and it's probably safe to use it [as long as textures are not deallocated manually](https://github.com/Rust-SDL2/rust-sdl2#about-the-unsafe_textures-feature), and looks like `rustzx` does not deallocate textures prematurely.

However, I'm not sure about regressions, as there are lots of changes in sdl2. For me, it runs very slowly in debug version (in release it's ok). Probably I should first build with first working version of sdl2 and compare.

### CODE REVIEW

**Comment by kolen** [comment]
I tried to update just `rustc-serialize`: it works and is also slow in debug version: #35. It can be applied first before doing full update of sdl version.

**Comment by pacmancoder** [comment]
FYI: #34 and #35 were merged.

**Comment by kolen** [comment]
What I've checked:
- [Sinclair's Research's ancient test program](http://www.worldofspectrum.org/infoseekid.cgi?id=0008884), everything seem to work, including all 48k keyboard keys
- Shock megademo, border effects and AY music work
- Setting larger `--scale`
- Kempston joystick

**Comment by pacmancoder** [comment]
Cool, thanks for the confirmation testing. I can merge this PR after conflicts will be resolved :smile:

**Pull request merged**
