### PR TITLE
Implement dropping files to main window (drag-n-drop)

### PR DESCRIPTION
**Pull request by kolen**
Added drag-n-drop functionality for files (from #29). Currently only `tap` and `sna` are supported:

- Dropping `.tap` file inserts it as current tape (without starting or autoloading, the same as `--tap` command line argument)
- Dropping `.sna` file loads snapshot immediately

Currently, there's no visual indication if drop is successful or failed (for `tap` it's invisible, as it just inserts tape).

File format is currently detected only by extension (case-insensitive).

Paths with malformed unicode are not supported: SDL [returns filename as `String`](https://docs.rs/sdl2/0.32.2/sdl2/event/enum.Event.html#variant.DropFile).

Added directory with files for tests, currently it's accessed via `CARGO_MANIFEST_DIR`, there are other approaches, like `env::current_exe`, but there's no standard idiomatic approach. Currently there's only one tap file.

**This branch is based on `update-sdl` branch (#33)**, as older SDL does not work on my machine.

### CODE REVIEW

**Comment by pacmancoder** [comment]
Hello! Thanks for the changes. Please, can you fix the conflicts so I can merge this branch to the master?

**Comment by pacmancoder** [comment]
Btw I think we should create an issue regarding the visual indication of the failure

**Comment by kolen** [comment]
I don't see merge conflicts, both for this branch and for `update-sdl`. Github also shows "This branch has no conflicts with the base branch".

```
~/items/rustzx % git merge update-sdl --no-ff --no-commit
Automatic merge went well; stopped before committing as requested
~/items/rustzx % git merge --abort
~/items/rustzx % git merge drag-n-drop-files --no-ff --no-commit
Automatic merge went well; stopped before committing as requested
```

This branch is based on `update-sdl` (#33), if you're going to use `merge --squash`, it would be better to first merge #33.

**Comment by pacmancoder** [comment]
@kolen Oh, I see, my Github GUI button for merge was in rebase mode so I haven't seen that it was able to merge it with merge commit, sorry :smile: 

Anyway, I'll merge it. Thank you for your contributions!

**Pull request merged**
